//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientCS.GabekoreApiService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GabekoreApiService.IService", CallbackContract=typeof(ClientCS.GabekoreApiService.IServiceCallback))]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/HelloWorld", ReplyAction="http://tempuri.org/IService/HelloWorldResponse")]
        string HelloWorld(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/HelloWorld", ReplyAction="http://tempuri.org/IService/HelloWorldResponse")]
        System.Threading.Tasks.Task<string> HelloWorldAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CalcPlus", ReplyAction="http://tempuri.org/IService/CalcPlusResponse")]
        int CalcPlus(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CalcPlus", ReplyAction="http://tempuri.org/IService/CalcPlusResponse")]
        System.Threading.Tasks.Task<int> CalcPlusAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CalcMinus", ReplyAction="http://tempuri.org/IService/CalcMinusResponse")]
        ClientCS.GabekoreApiService.CalcMinusResponse CalcMinus(ClientCS.GabekoreApiService.CalcMinusRequest request);
        
        // CODEGEN: 操作に複数の戻り値があるため、メッセージ コントラクトを生成しています。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CalcMinus", ReplyAction="http://tempuri.org/IService/CalcMinusResponse")]
        System.Threading.Tasks.Task<ClientCS.GabekoreApiService.CalcMinusResponse> CalcMinusAsync(ClientCS.GabekoreApiService.CalcMinusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UseTuple", ReplyAction="http://tempuri.org/IService/UseTupleResponse")]
        System.ValueTuple<string, int> UseTuple(string name, int age);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UseTuple", ReplyAction="http://tempuri.org/IService/UseTupleResponse")]
        System.Threading.Tasks.Task<System.ValueTuple<string, int>> UseTupleAsync(string name, int age);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetArgClass", ReplyAction="http://tempuri.org/IService/GetArgClassResponse")]
        ServiceIF.ObjIF.ArgClass GetArgClass();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetArgClass", ReplyAction="http://tempuri.org/IService/GetArgClassResponse")]
        System.Threading.Tasks.Task<ServiceIF.ObjIF.ArgClass> GetArgClassAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UseClass", ReplyAction="http://tempuri.org/IService/UseClassResponse")]
        ServiceIF.ObjIF.RetClass UseClass(ServiceIF.ObjIF.ArgClass argClass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UseClass", ReplyAction="http://tempuri.org/IService/UseClassResponse")]
        System.Threading.Tasks.Task<ServiceIF.ObjIF.RetClass> UseClassAsync(ServiceIF.ObjIF.ArgClass argClass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UseListClass", ReplyAction="http://tempuri.org/IService/UseListClassResponse")]
        ServiceIF.ObjIF.RetClass[] UseListClass(ServiceIF.ObjIF.ArgClass[] argClass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UseListClass", ReplyAction="http://tempuri.org/IService/UseListClassResponse")]
        System.Threading.Tasks.Task<ServiceIF.ObjIF.RetClass[]> UseListClassAsync(ServiceIF.ObjIF.ArgClass[] argClass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UseArray", ReplyAction="http://tempuri.org/IService/UseArrayResponse")]
        int[] UseArray(string[] numCharAry);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/UseArray", ReplyAction="http://tempuri.org/IService/UseArrayResponse")]
        System.Threading.Tasks.Task<int[]> UseArrayAsync(string[] numCharAry);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService/CallbackRegist")]
        void CallbackRegist(string push_id);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService/CallbackRegist")]
        System.Threading.Tasks.Task CallbackRegistAsync(string push_id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService/CallbackFunction")]
        void CallbackFunction(string push_id, string param1, int param2, double param3, string[] param4, ServiceIF.ObjIF.RetClass[] param5);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CalcMinus", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CalcMinusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int a;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int b;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int result;
        
        public CalcMinusRequest() {
        }
        
        public CalcMinusRequest(int a, int b, int result) {
            this.a = a;
            this.b = b;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CalcMinusResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CalcMinusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int result;
        
        public CalcMinusResponse() {
        }
        
        public CalcMinusResponse(int result) {
            this.result = result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : ClientCS.GabekoreApiService.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.DuplexClientBase<ClientCS.GabekoreApiService.IService>, ClientCS.GabekoreApiService.IService {
        
        public ServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public string HelloWorld(string name) {
            return base.Channel.HelloWorld(name);
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync(string name) {
            return base.Channel.HelloWorldAsync(name);
        }
        
        public int CalcPlus(int a, int b) {
            return base.Channel.CalcPlus(a, b);
        }
        
        public System.Threading.Tasks.Task<int> CalcPlusAsync(int a, int b) {
            return base.Channel.CalcPlusAsync(a, b);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientCS.GabekoreApiService.CalcMinusResponse ClientCS.GabekoreApiService.IService.CalcMinus(ClientCS.GabekoreApiService.CalcMinusRequest request) {
            return base.Channel.CalcMinus(request);
        }
        
        public void CalcMinus(int a, int b, ref int result) {
            ClientCS.GabekoreApiService.CalcMinusRequest inValue = new ClientCS.GabekoreApiService.CalcMinusRequest();
            inValue.a = a;
            inValue.b = b;
            inValue.result = result;
            ClientCS.GabekoreApiService.CalcMinusResponse retVal = ((ClientCS.GabekoreApiService.IService)(this)).CalcMinus(inValue);
            result = retVal.result;
        }
        
        public System.Threading.Tasks.Task<ClientCS.GabekoreApiService.CalcMinusResponse> CalcMinusAsync(ClientCS.GabekoreApiService.CalcMinusRequest request) {
            return base.Channel.CalcMinusAsync(request);
        }
        
        public System.ValueTuple<string, int> UseTuple(string name, int age) {
            return base.Channel.UseTuple(name, age);
        }
        
        public System.Threading.Tasks.Task<System.ValueTuple<string, int>> UseTupleAsync(string name, int age) {
            return base.Channel.UseTupleAsync(name, age);
        }
        
        public ServiceIF.ObjIF.ArgClass GetArgClass() {
            return base.Channel.GetArgClass();
        }
        
        public System.Threading.Tasks.Task<ServiceIF.ObjIF.ArgClass> GetArgClassAsync() {
            return base.Channel.GetArgClassAsync();
        }
        
        public ServiceIF.ObjIF.RetClass UseClass(ServiceIF.ObjIF.ArgClass argClass) {
            return base.Channel.UseClass(argClass);
        }
        
        public System.Threading.Tasks.Task<ServiceIF.ObjIF.RetClass> UseClassAsync(ServiceIF.ObjIF.ArgClass argClass) {
            return base.Channel.UseClassAsync(argClass);
        }
        
        public ServiceIF.ObjIF.RetClass[] UseListClass(ServiceIF.ObjIF.ArgClass[] argClass) {
            return base.Channel.UseListClass(argClass);
        }
        
        public System.Threading.Tasks.Task<ServiceIF.ObjIF.RetClass[]> UseListClassAsync(ServiceIF.ObjIF.ArgClass[] argClass) {
            return base.Channel.UseListClassAsync(argClass);
        }
        
        public int[] UseArray(string[] numCharAry) {
            return base.Channel.UseArray(numCharAry);
        }
        
        public System.Threading.Tasks.Task<int[]> UseArrayAsync(string[] numCharAry) {
            return base.Channel.UseArrayAsync(numCharAry);
        }
        
        public void CallbackRegist(string push_id) {
            base.Channel.CallbackRegist(push_id);
        }
        
        public System.Threading.Tasks.Task CallbackRegistAsync(string push_id) {
            return base.Channel.CallbackRegistAsync(push_id);
        }
    }
}
